name: DiscordSync
main: me.pilkeysek.DiscordSyncPlugin
version: 1.0
commands:
  discordsync:
    description: Configure DiscordSync
    usage: /discordsync (reload|config (get <key>|set <key> <value>|remove <key>))